# -*- coding: utf-8 -*-
"""Machine Learning - Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AFXtTpOl4HRo-oVdknukLIp94iVlBUfO
"""

from sklearn import tree,datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd #manipulação do CSV e dataset
url = "gender_classification_v7.csv"
data = pd.read_csv(url)

print('---------------data.info()-------------------')
data.info()
print('---------------data.head-------------------')
data.head
x = data.drop("gender",axis=1) #features
y = data['gender'] #labels
print('---------------print(x)-------------------')
print(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=42)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

predictions=clf.predict(x_test)
print('----------------------------------')
print("Preditos: ",predictions[:20])
print("Real:     ",y_test[:20].values)

print("Acurácia: ",accuracy_score(y_test,predictions))

print(clf.predict([[1,1,1,1,1,1,1]]))
print(clf.predict([[9,9,9,9,9,9,9]]))
print(clf.predict([[3,3,3,3,3,3,3]]))
print(clf.predict([[900,900,900,900,900,900,900]]))
a = int(input('long_hair: '))
b = int(input('forehead_width_cm: '))
c = int(input('forehead_height_cm: '))
d = int(input('nose_wide: '))
e = int(input('nose_long: '))
f = int(input('lips_thin: '))
g = int(input('distance_nose_to_lip_long: '))
pred = clf.predict([[a,b,c,d,e,f,g]])
print(pred)
#print(lookup_iris_name[pred[0]])

import pickle
pickle.dump(clf, open('model.pkl','wb')) # salvando o modelo de Machine Learning

